[package]
name = "zenwave"
version = "0.1.0"
edition = "2021"
authors = ["Lexo Liu<me@lexo.cool>"]
description = "Ergonomic HTTP client framework."
license = "MIT"

[dependencies]
async-trait = "0.1.74"
bytes = "1.5.0"
bytestr = "0.1.0"
cookie = { version = "0.18.0", features = ["percent-encode"] }
http-kit = { git = "https://github.com/lexoooooo/http-kit.git", rev = "7733014" ,features = ["json","form"]}
hyper = { version = "0.14.27", features = ["client","http1","tcp","stream"] }
once_cell = "1.18.0"
serde = "1.0.192"

[dev-dependencies]
tokio = { version="1.20.1", features=["macros","rt"] }
